backend:
  name: github
  repo: berekuk/berekuk.ru

media_folder: src/images

collections:
  - name: blog
    label: Blog
    folder: src/markdown-pages/blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: categories, label: Categories, widget: list }
